{
 "title": "Auth dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество ответов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(chat_space_grpc_chat_app_responses_total[5s])"
    }
   ]
  },
  {
   "title": "Квантили времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\nsum(rate(chat_space_grpc_chat_app_histogram_response_time_seconds_bucket[5s])) by (le, status)\n)"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(chat_space_grpc_chat_app_requests_total[5s])",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}