services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - local.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    env_file:
      - local.env
    environment:
      DB_HOST: pg-local

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
  postgres_volume_local:
  postgres_volume_prod:
  prometheus_data:
  grafana_data: