name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/merynayr"
  IMAGE_NAME: "test-server"
  CONTAINER_NAME: "test-server-container"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin $REGISTRY

      - name: Upload docker-compose.yml and prod.env
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSHKEY }}
          source: "./docker-compose.yml,./prod.env, ./local.env, ./migration_local.Dockerfile, ./migration_prod.Dockerfile, ./prod.Dockerfile"
          target: "~/.deploy/${{ github.event.repository.name }}/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            cd ~/.deploy/${{ github.event.repository.name }}
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Подставляем текущий TAG_NAME в docker-compose.yml
            sed -i "s|image: .*|image: $REGISTRY/$IMAGE_NAME:$TAG_NAME|g" docker-compose.yml
            
            # Логинимся в реестр
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin $REGISTRY
            
            # Обновляем образы и перезапускаем сервисы
            docker compose pull
            docker compose up -d --remove-orphans
